<script setup lang="ts">
import { nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { contactContent, navLinks } from '@/data/portfolio'
const isMenuOpen = ref(false)
const menuButton = ref<HTMLButtonElement | null>(null)
const closeMenu = async (restoreFocus = false) => { isMenuOpen.value = false; if (restoreFocus) { await nextTick(); menuButton.value?.focus() } }
const toggleMenu = () => { isMenuOpen.value = !isMenuOpen.value }
const handleKeydown = (event: KeyboardEvent) => { if (event.key === 'Escape' && isMenuOpen.value) void closeMenu(true) }
watch(isMenuOpen, (open) => { if (open) document.body.style.setProperty('overflow', 'hidden'); else document.body.style.removeProperty('overflow') })
onMounted(() => window.addEventListener('keydown', handleKeydown))
onBeforeUnmount(() => { window.removeEventListener('keydown', handleKeydown); document.body.style.removeProperty('overflow') })
</script>
<template><header class="sticky top-0 z-30 -mx-4 border-b border-[var(--color-line)] bg-[color:var(--color-canvas)/0.94] px-4 py-4 backdrop-blur sm:-mx-6 sm:px-6 lg:-mx-10 lg:px-10"><div class="mx-auto flex max-w-7xl items-center justify-between gap-4"><a href="#home" class="font-[var(--font-display)] text-sm font-semibold uppercase tracking-[0.08em]">Ilyass Bouissa</a><nav class="hidden items-center gap-1 lg:flex" aria-label="Navigation principale"><a v-for="link in navLinks" :key="link.id" :href="`#${link.id}`" class="min-h-11 px-3 py-3 text-sm text-[var(--color-muted)] transition hover:text-[var(--color-ink)]">{{ link.label }}</a></nav><a :href="`mailto:${contactContent.email}`" class="hidden min-h-11 items-center bg-[var(--color-accent)] px-4 text-sm font-semibold text-white hover:bg-[var(--color-accent-strong)] sm:inline-flex">Discuter</a><button ref="menuButton" type="button" class="inline-flex min-h-11 min-w-11 items-center justify-center border border-[var(--color-ink)] lg:hidden" aria-controls="mobile-navigation" :aria-expanded="isMenuOpen" :aria-label="isMenuOpen ? 'Fermer le menu' : 'Ouvrir le menu'" @click="toggleMenu"><svg v-if="!isMenuOpen" class="h-5 w-5" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 7h16M4 12h16M4 17h16" /></svg><svg v-else class="h-5 w-5" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M6 6l12 12M18 6 6 18" /></svg></button></div><nav v-if="isMenuOpen" id="mobile-navigation" class="mx-auto mt-4 grid max-w-7xl border-t border-[var(--color-line)] pt-3 lg:hidden" aria-label="Navigation mobile"><a v-for="link in navLinks" :key="link.id" :href="`#${link.id}`" class="min-h-11 py-2 text-sm font-medium" @click="closeMenu()">{{ link.label }}</a><a :href="`mailto:${contactContent.email}`" class="mt-2 min-h-11 py-2 text-sm font-semibold text-[var(--color-accent)]" @click="closeMenu()">Me contacter</a></nav></header></template>
